version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/zero-downtime-deployment-logging/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user